/**
 * version: alpha
 * theme: sula
 */
export declare const sulaChartsTheme: {
    seriesCnt: string;
    backgroundColor: string;
    titleColor: string;
    subtitleColor: string;
    textColorShow: boolean;
    textColor: string;
    markTextColor: string;
    color: string[];
    borderColor: string;
    borderWidth: number;
    visualMapColor: string[];
    legendTextColor: string;
    kColor: string;
    kColor0: string;
    kBorderColor: string;
    kBorderColor0: string;
    kBorderWidth: string;
    lineWidth: string;
    symbolSize: string;
    symbol: string;
    symbolBorderWidth: string;
    lineSmooth: boolean;
    graphLineWidth: string;
    graphLineColor: string;
    mapLabelColor: string;
    mapLabelColorE: string;
    mapBorderColor: string;
    mapBorderColorE: string;
    mapBorderWidth: number;
    mapBorderWidthE: number;
    mapAreaColor: string;
    mapAreaColorE: string;
    axes: {
        type: string;
        name: string;
        axisLineShow: boolean;
        axisLineColor: string;
        axisTickShow: boolean;
        axisTickColor: string;
        axisLabelShow: boolean;
        axisLabelColor: string;
        splitLineShow: boolean;
        splitLineColor: string[];
        splitAreaShow: boolean;
        splitAreaColor: string[];
    }[];
    axisSeperateSetting: boolean;
    toolboxColor: string;
    toolboxEmpasisColor: string;
    tooltipAxisColor: string;
    tooltipAxisWidth: number;
    timelineLineColor: string;
    timelineLineWidth: number;
    timelineItemColor: string;
    timelineItemColorE: string;
    timelineCheckColor: string;
    timelineCheckBorderColor: string;
    timelineItemBorderWidth: number;
    timelineControlColor: string;
    timelineControlBorderColor: string;
    timelineControlBorderWidth: number;
    timelineLabelColor: string;
    datazoomBackgroundColor: string;
    datazoomDataColor: string;
    datazoomFillColor: string;
    datazoomHandleColor: string;
    datazoomHandleWidth: string;
    datazoomLabelColor: string;
};
